# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import SmartObjectDetails_pb2 as SmartObjectDetails__pb2


class SmartObjectUpdateStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UpdateObject = channel.unary_unary(
                '/SmartObjectUpdate/UpdateObject',
                request_serializer=SmartObjectDetails__pb2.SmartObjectDetails.SerializeToString,
                response_deserializer=SmartObjectDetails__pb2.UpdateObjectReply.FromString,
                )


class SmartObjectUpdateServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UpdateObject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SmartObjectUpdateServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UpdateObject': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateObject,
                    request_deserializer=SmartObjectDetails__pb2.SmartObjectDetails.FromString,
                    response_serializer=SmartObjectDetails__pb2.UpdateObjectReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SmartObjectUpdate', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SmartObjectUpdate(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UpdateObject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SmartObjectUpdate/UpdateObject',
            SmartObjectDetails__pb2.SmartObjectDetails.SerializeToString,
            SmartObjectDetails__pb2.UpdateObjectReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
