# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: FindGatewayRequest.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='FindGatewayRequest.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x18\x46indGatewayRequest.proto\"\x14\n\x12\x46indGatewayRequestb\x06proto3'
)




_FINDGATEWAYREQUEST = _descriptor.Descriptor(
  name='FindGatewayRequest',
  full_name='FindGatewayRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=48,
)

DESCRIPTOR.message_types_by_name['FindGatewayRequest'] = _FINDGATEWAYREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FindGatewayRequest = _reflection.GeneratedProtocolMessageType('FindGatewayRequest', (_message.Message,), {
  'DESCRIPTOR' : _FINDGATEWAYREQUEST,
  '__module__' : 'FindGatewayRequest_pb2'
  # @@protoc_insertion_point(class_scope:FindGatewayRequest)
  })
_sym_db.RegisterMessage(FindGatewayRequest)


# @@protoc_insertion_point(module_scope)
