# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SmartObjectDetails.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='SmartObjectDetails.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x18SmartObjectDetails.proto\"8\n\x10SmartObjectsList\x12$\n\x07objects\x18\x01 \x03(\x0b\x32\x13.SmartObjectDetails\"\xee\x01\n\x12SmartObjectDetails\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\n\n\x02ip\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\x05\x12\n\n\x02id\x18\x08 \x01(\t\x12\x1e\n\x05light\x18\x04 \x01(\x0b\x32\r.LightDetailsH\x00\x12\x18\n\x02tv\x18\x05 \x01(\x0b\x32\n.TvDetailsH\x00\x12$\n\x02\x61\x63\x18\x06 \x01(\x0b\x32\x16.AirConditionerDetailsH\x00\x12\x30\n\x0btemp_sensor\x18\x07 \x01(\x0b\x32\x19.TemperatureSensorDetailsH\x00\x42\x10\n\x0eobject_details\"+\n\x0cLightDetails\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x63olor\x18\x02 \x01(\t\",\n\tTvDetails\x12\x0f\n\x07\x63hannel\x18\x01 \x01(\t\x12\x0e\n\x06volume\x18\x02 \x01(\x05\"O\n\x15\x41irConditionerDetails\x12\x13\n\x0btemperature\x18\x01 \x01(\x05\x12!\n\x04mode\x18\x02 \x01(\x0e\x32\x13.AirConditionerMode\"/\n\x18TemperatureSensorDetails\x12\x13\n\x0btemperature\x18\x01 \x01(\x05*F\n\x12\x41irConditionerMode\x12\x0c\n\x08\x46\x41N_MODE\x10\x00\x12\x0f\n\x0bSILENT_MODE\x10\x01\x12\x11\n\rEXTREME_CHILL\x10\x02\x62\x06proto3'
)

_AIRCONDITIONERMODE = _descriptor.EnumDescriptor(
  name='AirConditionerMode',
  full_name='AirConditionerMode',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='FAN_MODE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SILENT_MODE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='EXTREME_CHILL', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=548,
  serialized_end=618,
)
_sym_db.RegisterEnumDescriptor(_AIRCONDITIONERMODE)

AirConditionerMode = enum_type_wrapper.EnumTypeWrapper(_AIRCONDITIONERMODE)
FAN_MODE = 0
SILENT_MODE = 1
EXTREME_CHILL = 2



_SMARTOBJECTSLIST = _descriptor.Descriptor(
  name='SmartObjectsList',
  full_name='SmartObjectsList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='objects', full_name='SmartObjectsList.objects', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=84,
)


_SMARTOBJECTDETAILS = _descriptor.Descriptor(
  name='SmartObjectDetails',
  full_name='SmartObjectDetails',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='SmartObjectDetails.status', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ip', full_name='SmartObjectDetails.ip', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='port', full_name='SmartObjectDetails.port', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='id', full_name='SmartObjectDetails.id', index=3,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='light', full_name='SmartObjectDetails.light', index=4,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tv', full_name='SmartObjectDetails.tv', index=5,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ac', full_name='SmartObjectDetails.ac', index=6,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='temp_sensor', full_name='SmartObjectDetails.temp_sensor', index=7,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='object_details', full_name='SmartObjectDetails.object_details',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=87,
  serialized_end=325,
)


_LIGHTDETAILS = _descriptor.Descriptor(
  name='LightDetails',
  full_name='LightDetails',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='LightDetails.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='color', full_name='LightDetails.color', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=327,
  serialized_end=370,
)


_TVDETAILS = _descriptor.Descriptor(
  name='TvDetails',
  full_name='TvDetails',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='channel', full_name='TvDetails.channel', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='volume', full_name='TvDetails.volume', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=372,
  serialized_end=416,
)


_AIRCONDITIONERDETAILS = _descriptor.Descriptor(
  name='AirConditionerDetails',
  full_name='AirConditionerDetails',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='temperature', full_name='AirConditionerDetails.temperature', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mode', full_name='AirConditionerDetails.mode', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=418,
  serialized_end=497,
)


_TEMPERATURESENSORDETAILS = _descriptor.Descriptor(
  name='TemperatureSensorDetails',
  full_name='TemperatureSensorDetails',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='temperature', full_name='TemperatureSensorDetails.temperature', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=499,
  serialized_end=546,
)

_SMARTOBJECTSLIST.fields_by_name['objects'].message_type = _SMARTOBJECTDETAILS
_SMARTOBJECTDETAILS.fields_by_name['light'].message_type = _LIGHTDETAILS
_SMARTOBJECTDETAILS.fields_by_name['tv'].message_type = _TVDETAILS
_SMARTOBJECTDETAILS.fields_by_name['ac'].message_type = _AIRCONDITIONERDETAILS
_SMARTOBJECTDETAILS.fields_by_name['temp_sensor'].message_type = _TEMPERATURESENSORDETAILS
_SMARTOBJECTDETAILS.oneofs_by_name['object_details'].fields.append(
  _SMARTOBJECTDETAILS.fields_by_name['light'])
_SMARTOBJECTDETAILS.fields_by_name['light'].containing_oneof = _SMARTOBJECTDETAILS.oneofs_by_name['object_details']
_SMARTOBJECTDETAILS.oneofs_by_name['object_details'].fields.append(
  _SMARTOBJECTDETAILS.fields_by_name['tv'])
_SMARTOBJECTDETAILS.fields_by_name['tv'].containing_oneof = _SMARTOBJECTDETAILS.oneofs_by_name['object_details']
_SMARTOBJECTDETAILS.oneofs_by_name['object_details'].fields.append(
  _SMARTOBJECTDETAILS.fields_by_name['ac'])
_SMARTOBJECTDETAILS.fields_by_name['ac'].containing_oneof = _SMARTOBJECTDETAILS.oneofs_by_name['object_details']
_SMARTOBJECTDETAILS.oneofs_by_name['object_details'].fields.append(
  _SMARTOBJECTDETAILS.fields_by_name['temp_sensor'])
_SMARTOBJECTDETAILS.fields_by_name['temp_sensor'].containing_oneof = _SMARTOBJECTDETAILS.oneofs_by_name['object_details']
_AIRCONDITIONERDETAILS.fields_by_name['mode'].enum_type = _AIRCONDITIONERMODE
DESCRIPTOR.message_types_by_name['SmartObjectsList'] = _SMARTOBJECTSLIST
DESCRIPTOR.message_types_by_name['SmartObjectDetails'] = _SMARTOBJECTDETAILS
DESCRIPTOR.message_types_by_name['LightDetails'] = _LIGHTDETAILS
DESCRIPTOR.message_types_by_name['TvDetails'] = _TVDETAILS
DESCRIPTOR.message_types_by_name['AirConditionerDetails'] = _AIRCONDITIONERDETAILS
DESCRIPTOR.message_types_by_name['TemperatureSensorDetails'] = _TEMPERATURESENSORDETAILS
DESCRIPTOR.enum_types_by_name['AirConditionerMode'] = _AIRCONDITIONERMODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SmartObjectsList = _reflection.GeneratedProtocolMessageType('SmartObjectsList', (_message.Message,), {
  'DESCRIPTOR' : _SMARTOBJECTSLIST,
  '__module__' : 'SmartObjectDetails_pb2'
  # @@protoc_insertion_point(class_scope:SmartObjectsList)
  })
_sym_db.RegisterMessage(SmartObjectsList)

SmartObjectDetails = _reflection.GeneratedProtocolMessageType('SmartObjectDetails', (_message.Message,), {
  'DESCRIPTOR' : _SMARTOBJECTDETAILS,
  '__module__' : 'SmartObjectDetails_pb2'
  # @@protoc_insertion_point(class_scope:SmartObjectDetails)
  })
_sym_db.RegisterMessage(SmartObjectDetails)

LightDetails = _reflection.GeneratedProtocolMessageType('LightDetails', (_message.Message,), {
  'DESCRIPTOR' : _LIGHTDETAILS,
  '__module__' : 'SmartObjectDetails_pb2'
  # @@protoc_insertion_point(class_scope:LightDetails)
  })
_sym_db.RegisterMessage(LightDetails)

TvDetails = _reflection.GeneratedProtocolMessageType('TvDetails', (_message.Message,), {
  'DESCRIPTOR' : _TVDETAILS,
  '__module__' : 'SmartObjectDetails_pb2'
  # @@protoc_insertion_point(class_scope:TvDetails)
  })
_sym_db.RegisterMessage(TvDetails)

AirConditionerDetails = _reflection.GeneratedProtocolMessageType('AirConditionerDetails', (_message.Message,), {
  'DESCRIPTOR' : _AIRCONDITIONERDETAILS,
  '__module__' : 'SmartObjectDetails_pb2'
  # @@protoc_insertion_point(class_scope:AirConditionerDetails)
  })
_sym_db.RegisterMessage(AirConditionerDetails)

TemperatureSensorDetails = _reflection.GeneratedProtocolMessageType('TemperatureSensorDetails', (_message.Message,), {
  'DESCRIPTOR' : _TEMPERATURESENSORDETAILS,
  '__module__' : 'SmartObjectDetails_pb2'
  # @@protoc_insertion_point(class_scope:TemperatureSensorDetails)
  })
_sym_db.RegisterMessage(TemperatureSensorDetails)


# @@protoc_insertion_point(module_scope)
